### ISSUE TITLE
Test-Time Augmentation and Implausible Pose Suppression

### ISSUE THREAD

**Issue by steb6** [tobibaum/metrabs_trt#2]
Hi, I am using MetrABS for a research project and I find amazing that someone else was trying to speed it up with TensorRT!
Thanks for making this repo which allowed me to add the signatures and export the models as Onnx.
I am trying to do the same thing that you did, but in Python.
I managed to do everything following your instructions (Yolov4 and BackBone with TensorRT, the MetrabsHeads with TensorFlow), but the results that I am achieving are much worse than the one that comes out from `model.detect_poses`.
I suppose that this happens because we are not doing test-time augmentation and implausible pose suppression.
The result that you are obtaining are in line with the one of `model.detect_poses`?

**Comment by mrpositron** [comment]
Hello @StefanoBerti!

Have you solved this problem?

**Comment by steb6** [comment]
Hi @mrpositron,
the problem here was that he was not using homography as a preprocessing phase for the backbone.
Take a look to [my repository](https://github.com/StefanoBerti/ISBFSAR/tree/main/modules/hpe) where I managed to accelerate the best model of MetrABS at 50 FPS

p.s. the README is not updated, open an issue if you need anything
